name: todo_list
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.10.6

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  collection: ^1.18.0
  dio: ^5.3.3
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  equatable: ^2.0.5
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3  
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1  
  flutter_svg: ^2.0.7 
  flutter_svg_provider: ^1.0.6
  fpdart: ^1.1.0 
  freezed_annotation: ^2.4.1  
  google_fonts: ^6.1.0
  intl: ^0.18.1
  json_annotation: 4.8.1
  logger: ^1.4.0
  path: 1.8.3
  path_provider: ^2.1.1
  provider: 6.0.5
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  surf_logger: 1.1.0
  uuid: ^4.2.1


dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  elementary_test: ^2.0.0
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2  
  golden_toolkit: 0.15.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  retrofit_generator: ^8.0.2
  spider: ^4.2.2
  surf_lint_rules: 3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
